apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonos-deployment # ej: apuestas-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bonos
  template:
    metadata:
      labels:
        app: bonos
    spec:
      containers:
      - name: bonos
        image: 914091100375.dkr.ecr.us-east-1.amazonaws.com/bonos-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "postgres-service"
        envFrom:
        - secretRef:
            name: casino-secrets
        # CAMBIO: Agregamos las sondas de salud que definiste en tu código
        livenessProbe:
          httpGet:
            path: /livez
            port: 3000
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 3000
          initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: bonos-service
spec:
  type: ClusterIP
  selector:
    app: bonos
  ports:
  - port: 3000
    targetPort: 3000